In [1]:
nifti_file_path = "/Users/joachimpfefferkorn/repos/neurovolume/media/openneuro/sub-01_T1w.nii"

In [2]:
from nifti_reader import read_nifti
from functions import *
import nibabel as nib

In [3]:
custom_img = read_nifti(nifti_file_path)

Detected endianness: Little sign: <
pixdim:  (1.0, 0.47850000858306885, 0.47850000858306885, 0.5, 0.0, 0.0, 0.0, 0.0)
xyzt units <class 'int'> 2
 slice code 0
🟦 qform code  (1,)
🟦 sform code  (1,)
🟩 srow_x (0.47849801182746887, -0.0012153900461271405, 0.0, -119.98899841308594)
   srow_y (0.0012153900461271405, 0.47849801182746887, 0.0, -104.5199966430664)
   srow_z (0.0, 0.0, 0.5, -84.24569702148438)
Header Size: 348
Bitpix: 16
Datatype: signed short, 16
Vox Offset: 352.0
dimensions: (3, 512, 512, 296, 1, 1, 1, 1)
Datatype num:  4
scl_slope: 0.14433500170707703, scl_inter: 4729.56982421875
number of bits:  77594624 
number of bytes:  155189248
dtype override:  int16
Using dtype: int16, Endianness: =
voxels 77594624 <class 'numpy.ndarray'> (77594624,)
Expected voxel count: 77594624
Actual voxel count: 77594624
Applied intensity scaling
volume shape:  (512, 512, 296, 1)
Volume dtype float32


In [4]:
nib_img = nib.load(nifti_file_path)
print(nib_img)


<class 'nibabel.nifti1.Nifti1Image'>
data shape (512, 512, 296)
affine:
[[ 4.78498012e-01 -1.21539005e-03  0.00000000e+00 -1.19988998e+02]
 [ 1.21539005e-03  4.78498012e-01  0.00000000e+00 -1.04519997e+02]
 [ 0.00000000e+00  0.00000000e+00  5.00000000e-01 -8.42456970e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : np.bytes_(b'')
db_name         : np.bytes_(b'')
extents         : 0
session_error   : 0
regular         : np.bytes_(b'r')
dim_info        : 54
dim             : [  3 512 512 296   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.     0.4785 0.4785 0.5    0.     0.     0.     0.    ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units    

In [6]:
nib_array = nib_img.get_fdata()

In [22]:
print(type(nib_array))

<class 'numpy.ndarray'>


In [8]:
import numpy as np
print(np.min(custom_img), np.max(custom_img))
print(np.min(nib_array), np.max(nib_array))

0.00048828125 9458.994
0.00048828125 9458.994825154543


In [16]:
nib_unscaled = nib_img.dataobj.get_unscaled()

In [18]:
explore_3D_vol(nib_unscaled, dim='y')

interactive(children=(IntSlider(value=255, description='slice', max=511), Output()), _dom_classes=('widget-int…

In [19]:
explore_3D_vol(nib_array, dim='y')

interactive(children=(IntSlider(value=255, description='slice', max=511), Output()), _dom_classes=('widget-int…

In [12]:
print(custom_img.shape)
print(nib_array.shape)

(512, 512, 296, 1)
(512, 512, 296)


In [47]:
#s_custom_img = np.squeeze(custom_img, axis=-1)
s_custom_img = custom_img[...,0]
print(s_custom_img.shape)

(512, 512, 296)


In [48]:
explore_3D_vol(s_custom_img, dim='y')

interactive(children=(IntSlider(value=255, description='slice', max=511), Output()), _dom_classes=('widget-int…

In [ ]:
print(ants_vol_test.numpy().dtype)

# Reorder the Slices with Nibabel Source Code

In [20]:
import orientations

In [36]:
# Hard coding affine for now (we got it from the binary parsing srow)
affine = np.array([
    [0.4785, -0.0012,  0.0,  -119.989],
    [0.0012,  0.4785,  0.0,  -104.520],
    [0.0,     0.0,     0.5,  -84.246],
    [0.0,     0.0,     0.0,   1.0]  # Homogeneous coordinates
])

print(affine)

[[ 4.78500e-01 -1.20000e-03  0.00000e+00 -1.19989e+02]
 [ 1.20000e-03  4.78500e-01  0.00000e+00 -1.04520e+02]
 [ 0.00000e+00  0.00000e+00  5.00000e-01 -8.42460e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]


In [37]:
orientation = orientations.io_orientation(affine)

In [38]:
print(orientation)

[[0. 1.]
 [1. 1.]
 [2. 1.]]


In [49]:
oriented_arr = orientations.apply_orientation(s_custom_img, orientation)

In [50]:
explore_3D_vol(oriented_arr, dim='y')

interactive(children=(IntSlider(value=255, description='slice', max=511), Output()), _dom_classes=('widget-int…

In [45]:
nib_header = nib_img.header
print(nib_header.get_slice_times())

HeaderDataError: Cannot get slice times when slice code is "unknown"