In [1]:
from scivol import *

In [2]:
import numpy as np

grid = np.random.rand(30, 30, 30)
grid2 = np.random.rand(30, 30, 30)
grid3 = np.random.rand(30, 30, 30)
grids = [Grid("ham", [grid]), Grid("spam", [grid2]), Grid("flan", [grid3])]

In [3]:
test_scivol = Scivol("testing")
test_scivol.add_grids(grids)

writing ham to grid
writing spam to grid
writing flan to grid


In [4]:
print(test_scivol.grids['ham'])

for g in test_scivol.grids:
    print(g)
    print(test_scivol.grids[g]['frames'][0][0][0])

{'frames': [[[[0.18626420021329293, 0.2868179097482787, 0.06637055526487523, 0.14695206593005838, 0.8604275612989586, 0.8139698954229335, 0.8231193731335642, 0.6436476403581602, 0.13989574391643778, 0.44413907663591734, 0.5353012376749603, 0.17174606699519623, 0.40686376652422473, 0.08004670753653376, 0.4298010017083608, 0.7850758873537214, 0.2285094328990468, 0.30916198006304485, 0.7306094070304718, 0.019731571794425085, 0.6328247786037764, 0.8523984182707145, 0.8272149560791159, 0.8141615601336938, 0.10833448142984281, 0.3618527553374091, 0.624712830366452, 0.1273955130392852, 0.5929197955848415, 0.8505991854392652], [0.5187966314318525, 0.6470818322001578, 0.2120324658623336, 0.4267452732809215, 0.09474094515416631, 0.4389160436600633, 0.5815049039277124, 0.5547044405889802, 0.2782389043479768, 0.4993581163463404, 0.9195432130483036, 0.6850043923923986, 0.05471540065400815, 0.8070102510730045, 0.17244623956276062, 0.2426269496227006, 0.12369768369996881, 0.48304540623471315, 0.85659

In [5]:
print(test_scivol)

testing
tolerance: 0.0
affine: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
grids:
    - ham
    - spam
    - flan

